name: mobile_app
description: "Zenno - Developer Analytics & Productivity"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Firebase
  firebase_core: ^4.7.0
  firebase_auth: ^6.4.0
  google_sign_in: ^6.2.2

  # Navigation
  go_router: ^14.8.1

  # State management
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

  # Network
  dio: ^5.8.0+1
  pretty_dio_logger: ^1.4.0

  # Models
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0

  # Chat realtime
  socket_io_client: ^3.0.2

  # UI
  flutter_svg: ^2.0.17
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  fl_chart: ^0.70.2
  image_picker: ^1.1.2

  # Storage
  shared_preferences: ^2.5.3

  # Utils
  intl: ^0.20.2
  url_launcher: ^6.3.1
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.15
  freezed: ^3.0.0
  json_serializable: ^6.9.5
  riverpod_generator: ^2.6.5
  custom_lint: ^0.7.5
  riverpod_lint: ^2.6.5

flutter:
  uses-material-design: true
  assets:
    - .env
